// Generated by gencpp from file yamnet_coral/AudioClassification.msg
// DO NOT EDIT!


#ifndef YAMNET_CORAL_MESSAGE_AUDIOCLASSIFICATION_H
#define YAMNET_CORAL_MESSAGE_AUDIOCLASSIFICATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yamnet_coral
{
template <class ContainerAllocator>
struct AudioClassification_
{
  typedef AudioClassification_<ContainerAllocator> Type;

  AudioClassification_()
    : label()
    , confidence(0.0)
    , rms(0.0)
    , stamp()  {
    }
  AudioClassification_(const ContainerAllocator& _alloc)
    : label(_alloc)
    , confidence(0.0)
    , rms(0.0)
    , stamp()  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _label_type;
  _label_type label;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef float _rms_type;
  _rms_type rms;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::yamnet_coral::AudioClassification_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yamnet_coral::AudioClassification_<ContainerAllocator> const> ConstPtr;

}; // struct AudioClassification_

typedef ::yamnet_coral::AudioClassification_<std::allocator<void> > AudioClassification;

typedef boost::shared_ptr< ::yamnet_coral::AudioClassification > AudioClassificationPtr;
typedef boost::shared_ptr< ::yamnet_coral::AudioClassification const> AudioClassificationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yamnet_coral::AudioClassification_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yamnet_coral::AudioClassification_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yamnet_coral::AudioClassification_<ContainerAllocator1> & lhs, const ::yamnet_coral::AudioClassification_<ContainerAllocator2> & rhs)
{
  return lhs.label == rhs.label &&
    lhs.confidence == rhs.confidence &&
    lhs.rms == rhs.rms &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yamnet_coral::AudioClassification_<ContainerAllocator1> & lhs, const ::yamnet_coral::AudioClassification_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yamnet_coral

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::yamnet_coral::AudioClassification_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yamnet_coral::AudioClassification_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yamnet_coral::AudioClassification_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yamnet_coral::AudioClassification_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yamnet_coral::AudioClassification_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yamnet_coral::AudioClassification_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yamnet_coral::AudioClassification_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10f8093929cee2e0e62a2607a78d22df";
  }

  static const char* value(const ::yamnet_coral::AudioClassification_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10f8093929cee2e0ULL;
  static const uint64_t static_value2 = 0xe62a2607a78d22dfULL;
};

template<class ContainerAllocator>
struct DataType< ::yamnet_coral::AudioClassification_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yamnet_coral/AudioClassification";
  }

  static const char* value(const ::yamnet_coral::AudioClassification_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yamnet_coral::AudioClassification_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string label\n"
"float32 confidence\n"
"float32 rms\n"
"time stamp\n"
;
  }

  static const char* value(const ::yamnet_coral::AudioClassification_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yamnet_coral::AudioClassification_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.confidence);
      stream.next(m.rms);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AudioClassification_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yamnet_coral::AudioClassification_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yamnet_coral::AudioClassification_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.label);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "rms: ";
    Printer<float>::stream(s, indent + "  ", v.rms);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YAMNET_CORAL_MESSAGE_AUDIOCLASSIFICATION_H
